<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>974ec58b-e3ec-4705-95df-a0f5c1b5f3d6</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\AIChatApp.Core\AIChatApp.Core.csproj" />
  </ItemGroup>

</Project>
